// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2GkekdHMUCEok0w8buEcW8abyYHLjDPo',
    appId: '1:657683083695:android:90b052411e65ed40497f5a',
    messagingSenderId: '657683083695',
    projectId: 'abdou-sat-pro',
    storageBucket: 'abdou-sat-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqolx56tSUj9ceJsH5fO0yxMJIENL6TZg',
    appId: '1:657683083695:ios:b7fc3ebd7555d2d3497f5a',
    messagingSenderId: '657683083695',
    projectId: 'abdou-sat-pro',
    storageBucket: 'abdou-sat-pro.appspot.com',
    iosBundleId: 'com.example.abdousat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqolx56tSUj9ceJsH5fO0yxMJIENL6TZg',
    appId: '1:657683083695:ios:b7fc3ebd7555d2d3497f5a',
    messagingSenderId: '657683083695',
    projectId: 'abdou-sat-pro',
    storageBucket: 'abdou-sat-pro.appspot.com',
    iosBundleId: 'com.example.abdousat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0iTb2cHxo7dTclS0uuijM_gVHjFi1snc',
    appId: '1:657683083695:web:7680840d319db009497f5a',
    messagingSenderId: '657683083695',
    projectId: 'abdou-sat-pro',
    authDomain: 'abdou-sat-pro.firebaseapp.com',
    storageBucket: 'abdou-sat-pro.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0iTb2cHxo7dTclS0uuijM_gVHjFi1snc',
    appId: '1:657683083695:web:7680840d319db009497f5a',
    messagingSenderId: '657683083695',
    projectId: 'abdou-sat-pro',
    authDomain: 'abdou-sat-pro.firebaseapp.com',
    storageBucket: 'abdou-sat-pro.appspot.com',
  );

}